# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Cuestionario')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, verbose_name='Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, verbose_name='Respuesta')),
                ('valor', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuestas',
            field=models.ManyToManyField(to='cuestionario.Respuesta'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='preguntas',
            field=models.ManyToManyField(to='cuestionario.Pregunta'),
        ),
    ]
